services:
  app:
    build: .
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aws_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0204
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.22-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0204
      POSTGRES_DB: aws_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net

  redis:
    image: redis:8.2.2-alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "0204"]
    restart: always
    ports:
      - "6379:6379"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres-data: